"""empty message

Revision ID: c80a73f9b985
Revises: 50ccbc80fd47
Create Date: 2023-06-21 12:22:51.704940

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c80a73f9b985'
down_revision = '50ccbc80fd47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('strains', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subtype', sa.Enum('Indica', 'Sativa', 'Hybrid'), nullable=True))
        batch_op.add_column(sa.Column('thc_concentration', sa.Float(), nullable=True))
        batch_op.drop_column('effects')
        batch_op.drop_column('flavor')
        batch_op.drop_column('terpene_profile')
        batch_op.drop_column('delta_nine_concentration')
        batch_op.drop_column('uses')
        batch_op.drop_column('type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('strains', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', mysql.VARCHAR(length=128), nullable=True))
        batch_op.add_column(sa.Column('uses', mysql.VARCHAR(length=128), nullable=True))
        batch_op.add_column(sa.Column('delta_nine_concentration', mysql.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('terpene_profile', mysql.VARCHAR(length=128), nullable=True))
        batch_op.add_column(sa.Column('flavor', mysql.VARCHAR(length=128), nullable=True))
        batch_op.add_column(sa.Column('effects', mysql.VARCHAR(length=128), nullable=True))
        batch_op.drop_column('thc_concentration')
        batch_op.drop_column('subtype')

    # ### end Alembic commands ###
