#!/bin/bash

# Install Nginx
sudo apt update
sudo apt install -y nginx

# Remove the existing symbolic link and configuration file
sudo rm /etc/nginx/sites-enabled/strain.gg

# Create a new configuration file
sudo bash -c 'cat > /etc/nginx/sites-available/strain.gg << EOL
server {
    listen 80;
    server_name strain.gg;

    location / {
        return 301 /clouds/;
    }

    location /clouds/ {
        proxy_pass http://127.0.0.1:5000;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
    }
}
EOL'

# Create a new symbolic link
sudo ln -s /etc/nginx/sites-available/strain.gg /etc/nginx/sites-enabled/strain.gg

# Test the new configuration
sudo nginx -t

# Reload Nginx with the new configuration
sudo systemctl reload nginx
