#!/usr/bin/env bash

sudo apt update
sudo apt install -y nginx

# Remove the default configuration
sudo rm -f /etc/nginx/sites-enabled/default

# Remove the old Nginx configuration files
sudo rm -r /etc/nginx/sites-available/strain.gg
sudo rm -r /etc/nginx/sites-enabled/strain.gg

# Create a new Nginx configuration file
sudo bash -c "cat > /etc/nginx/sites-available/strain.gg << 'EOL'
server {
    listen 80;
    server_name strain.gg www.strain.gg;

    location / {
        return 301 $scheme://$host/clouds/;
    }

    location /clouds/ {
        proxy_pass http://127.0.0.1:5050;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /static/ {
        alias /var/www/strain.gg/app/static/;
        expires 30d;
        autoindex off;
    }
}
EOL"

# Create a symbolic link to enable the new site configuration
sudo ln -sf /etc/nginx/sites-available/strain.gg /etc/nginx/sites-enabled/

# Test the Nginx configuration
sudo nginx -t

# Reload the Nginx service to apply the new configuration
sudo systemctl reload nginx
