#!/bin/bash

# Update package list and install nginx
sudo apt-get update
sudo apt-get install -y nginx

# Create a new nginx configuration file for strain.gg
cat > strain.gg <<EOL
server {
    listen 80;
    server_name strain.gg www.strain.gg;

    location / {
        return 301 /clouds/;
    }

    location /clouds/ {
        alias /var/www/strain.gg/static;
        try_files \$uri @strain_gg_clouds;
    }

    location @strain_gg_clouds {
        proxy_pass http://127.0.0.1:5050;
        proxy_set_header Host \$http_host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
    }
}
EOL

# Remove existing symbolic link and configuration file
sudo rm -f /etc/nginx/sites-enabled/strain.gg
sudo rm -f /etc/nginx/sites-available/strain.gg

# Create a new symbolic link in the sites-enabled directory
sudo mv strain.gg /etc/nginx/sites-available/
sudo ln -s /etc/nginx/sites-available/strain.gg /etc/nginx/sites-enabled/

# Test nginx configuration
sudo nginx -t

# Reload nginx service
sudo systemctl reload nginx
